GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to pgbouncer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to pgbouncer;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to pgbouncer;